// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int event_type;
 *     int client_fd;
 *     char buffer[4096];
 *     size_t len;
 * }
 * }
 */
public class conn_info {

    conn_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_INT.withName("event_type"),
        uring_syscalls_h.C_INT.withName("client_fd"),
        MemoryLayout.sequenceLayout(4096, uring_syscalls_h.C_CHAR).withName("buffer"),
        uring_syscalls_h.C_LONG.withName("len")
    ).withName("$anon$19:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt event_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("event_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static final OfInt event_type$layout() {
        return event_type$LAYOUT;
    }

    private static final long event_type$OFFSET = $LAYOUT.byteOffset(groupElement("event_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static final long event_type$offset() {
        return event_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static int event_type(MemorySegment struct) {
        return struct.get(event_type$LAYOUT, event_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int event_type
     * }
     */
    public static void event_type(MemorySegment struct, int fieldValue) {
        struct.set(event_type$LAYOUT, event_type$OFFSET, fieldValue);
    }

    private static final OfInt client_fd$LAYOUT = (OfInt)$LAYOUT.select(groupElement("client_fd"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int client_fd
     * }
     */
    public static final OfInt client_fd$layout() {
        return client_fd$LAYOUT;
    }

    private static final long client_fd$OFFSET = $LAYOUT.byteOffset(groupElement("client_fd"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int client_fd
     * }
     */
    public static final long client_fd$offset() {
        return client_fd$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int client_fd
     * }
     */
    public static int client_fd(MemorySegment struct) {
        return struct.get(client_fd$LAYOUT, client_fd$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int client_fd
     * }
     */
    public static void client_fd(MemorySegment struct, int fieldValue) {
        struct.set(client_fd$LAYOUT, client_fd$OFFSET, fieldValue);
    }

    private static final SequenceLayout buffer$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static final SequenceLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = $LAYOUT.byteOffset(groupElement("buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.asSlice(buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buffer$OFFSET, buffer$LAYOUT.byteSize());
    }

    private static long[] buffer$DIMS = { 4096 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static long[] buffer$dimensions() {
        return buffer$DIMS;
    }
    private static final VarHandle buffer$ELEM_HANDLE = buffer$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static byte buffer(MemorySegment struct, long index0) {
        return (byte)buffer$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char buffer[4096]
     * }
     */
    public static void buffer(MemorySegment struct, long index0, byte fieldValue) {
        buffer$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfLong len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t len
     * }
     */
    public static final OfLong len$layout() {
        return len$LAYOUT;
    }

    private static final long len$OFFSET = $LAYOUT.byteOffset(groupElement("len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t len
     * }
     */
    public static final long len$offset() {
        return len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t len
     * }
     */
    public static long len(MemorySegment struct) {
        return struct.get(len$LAYOUT, len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t len
     * }
     */
    public static void len(MemorySegment struct, long fieldValue) {
        struct.set(len$LAYOUT, len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

