// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct gcs_context {
 *     struct _aarch64_ctx head;
 *     __u64 gcspr;
 *     __u64 features_enabled;
 *     __u64 reserved;
 * }
 * }
 */
public class gcs_context {

    gcs_context() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _aarch64_ctx.layout().withName("head"),
        uring_syscalls_h.C_LONG_LONG.withName("gcspr"),
        uring_syscalls_h.C_LONG_LONG.withName("features_enabled"),
        uring_syscalls_h.C_LONG_LONG.withName("reserved")
    ).withName("gcs_context");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout head$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("head"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct _aarch64_ctx head
     * }
     */
    public static final GroupLayout head$layout() {
        return head$LAYOUT;
    }

    private static final long head$OFFSET = $LAYOUT.byteOffset(groupElement("head"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct _aarch64_ctx head
     * }
     */
    public static final long head$offset() {
        return head$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct _aarch64_ctx head
     * }
     */
    public static MemorySegment head(MemorySegment struct) {
        return struct.asSlice(head$OFFSET, head$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct _aarch64_ctx head
     * }
     */
    public static void head(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, head$OFFSET, head$LAYOUT.byteSize());
    }

    private static final OfLong gcspr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("gcspr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 gcspr
     * }
     */
    public static final OfLong gcspr$layout() {
        return gcspr$LAYOUT;
    }

    private static final long gcspr$OFFSET = $LAYOUT.byteOffset(groupElement("gcspr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 gcspr
     * }
     */
    public static final long gcspr$offset() {
        return gcspr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 gcspr
     * }
     */
    public static long gcspr(MemorySegment struct) {
        return struct.get(gcspr$LAYOUT, gcspr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 gcspr
     * }
     */
    public static void gcspr(MemorySegment struct, long fieldValue) {
        struct.set(gcspr$LAYOUT, gcspr$OFFSET, fieldValue);
    }

    private static final OfLong features_enabled$LAYOUT = (OfLong)$LAYOUT.select(groupElement("features_enabled"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 features_enabled
     * }
     */
    public static final OfLong features_enabled$layout() {
        return features_enabled$LAYOUT;
    }

    private static final long features_enabled$OFFSET = $LAYOUT.byteOffset(groupElement("features_enabled"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 features_enabled
     * }
     */
    public static final long features_enabled$offset() {
        return features_enabled$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 features_enabled
     * }
     */
    public static long features_enabled(MemorySegment struct) {
        return struct.get(features_enabled$LAYOUT, features_enabled$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 features_enabled
     * }
     */
    public static void features_enabled(MemorySegment struct, long fieldValue) {
        struct.set(features_enabled$LAYOUT, features_enabled$OFFSET, fieldValue);
    }

    private static final OfLong reserved$LAYOUT = (OfLong)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 reserved
     * }
     */
    public static final OfLong reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = $LAYOUT.byteOffset(groupElement("reserved"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 reserved
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 reserved
     * }
     */
    public static long reserved(MemorySegment struct) {
        return struct.get(reserved$LAYOUT, reserved$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 reserved
     * }
     */
    public static void reserved(MemorySegment struct, long fieldValue) {
        struct.set(reserved$LAYOUT, reserved$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

