// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_region_desc {
 *     __u64 user_addr;
 *     __u64 size;
 *     __u32 flags;
 *     __u32 id;
 *     __u64 mmap_offset;
 *     __u64 __resv[4];
 * }
 * }
 */
public class io_uring_region_desc {

    io_uring_region_desc() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_LONG_LONG.withName("user_addr"),
        uring_syscalls_h.C_LONG_LONG.withName("size"),
        uring_syscalls_h.C_INT.withName("flags"),
        uring_syscalls_h.C_INT.withName("id"),
        uring_syscalls_h.C_LONG_LONG.withName("mmap_offset"),
        MemoryLayout.sequenceLayout(4, uring_syscalls_h.C_LONG_LONG).withName("__resv")
    ).withName("io_uring_region_desc");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong user_addr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static final OfLong user_addr$layout() {
        return user_addr$LAYOUT;
    }

    private static final long user_addr$OFFSET = $LAYOUT.byteOffset(groupElement("user_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static final long user_addr$offset() {
        return user_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static long user_addr(MemorySegment struct) {
        return struct.get(user_addr$LAYOUT, user_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static void user_addr(MemorySegment struct, long fieldValue) {
        struct.set(user_addr$LAYOUT, user_addr$OFFSET, fieldValue);
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfLong mmap_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mmap_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 mmap_offset
     * }
     */
    public static final OfLong mmap_offset$layout() {
        return mmap_offset$LAYOUT;
    }

    private static final long mmap_offset$OFFSET = $LAYOUT.byteOffset(groupElement("mmap_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 mmap_offset
     * }
     */
    public static final long mmap_offset$offset() {
        return mmap_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 mmap_offset
     * }
     */
    public static long mmap_offset(MemorySegment struct) {
        return struct.get(mmap_offset$LAYOUT, mmap_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 mmap_offset
     * }
     */
    public static void mmap_offset(MemorySegment struct, long fieldValue) {
        struct.set(mmap_offset$LAYOUT, mmap_offset$OFFSET, fieldValue);
    }

    private static final SequenceLayout __resv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__resv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static final SequenceLayout __resv$layout() {
        return __resv$LAYOUT;
    }

    private static final long __resv$OFFSET = $LAYOUT.byteOffset(groupElement("__resv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static final long __resv$offset() {
        return __resv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static MemorySegment __resv(MemorySegment struct) {
        return struct.asSlice(__resv$OFFSET, __resv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static void __resv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __resv$OFFSET, __resv$LAYOUT.byteSize());
    }

    private static long[] __resv$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static long[] __resv$dimensions() {
        return __resv$DIMS;
    }
    private static final VarHandle __resv$ELEM_HANDLE = __resv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static long __resv(MemorySegment struct, long index0) {
        return (long)__resv$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u64 __resv[4]
     * }
     */
    public static void __resv(MemorySegment struct, long index0, long fieldValue) {
        __resv$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

