// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_mem_region_reg {
 *     __u64 region_uptr;
 *     __u64 flags;
 *     __u64 __resv[2];
 * }
 * }
 */
public class io_uring_mem_region_reg {

    io_uring_mem_region_reg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_LONG_LONG.withName("region_uptr"),
        uring_syscalls_h.C_LONG_LONG.withName("flags"),
        MemoryLayout.sequenceLayout(2, uring_syscalls_h.C_LONG_LONG).withName("__resv")
    ).withName("io_uring_mem_region_reg");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong region_uptr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("region_uptr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 region_uptr
     * }
     */
    public static final OfLong region_uptr$layout() {
        return region_uptr$LAYOUT;
    }

    private static final long region_uptr$OFFSET = $LAYOUT.byteOffset(groupElement("region_uptr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 region_uptr
     * }
     */
    public static final long region_uptr$offset() {
        return region_uptr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 region_uptr
     * }
     */
    public static long region_uptr(MemorySegment struct) {
        return struct.get(region_uptr$LAYOUT, region_uptr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 region_uptr
     * }
     */
    public static void region_uptr(MemorySegment struct, long fieldValue) {
        struct.set(region_uptr$LAYOUT, region_uptr$OFFSET, fieldValue);
    }

    private static final OfLong flags$LAYOUT = (OfLong)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 flags
     * }
     */
    public static final OfLong flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 flags
     * }
     */
    public static long flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 flags
     * }
     */
    public static void flags(MemorySegment struct, long fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final SequenceLayout __resv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__resv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static final SequenceLayout __resv$layout() {
        return __resv$LAYOUT;
    }

    private static final long __resv$OFFSET = $LAYOUT.byteOffset(groupElement("__resv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static final long __resv$offset() {
        return __resv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static MemorySegment __resv(MemorySegment struct) {
        return struct.asSlice(__resv$OFFSET, __resv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static void __resv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __resv$OFFSET, __resv$LAYOUT.byteSize());
    }

    private static long[] __resv$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static long[] __resv$dimensions() {
        return __resv$DIMS;
    }
    private static final VarHandle __resv$ELEM_HANDLE = __resv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static long __resv(MemorySegment struct, long index0) {
        return (long)__resv$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u64 __resv[2]
     * }
     */
    public static void __resv(MemorySegment struct, long index0, long fieldValue) {
        __resv$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

