// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_cqwait_reg_arg {
 *     __u32 flags;
 *     __u32 struct_size;
 *     __u32 nr_entries;
 *     __u32 pad;
 *     __u64 user_addr;
 *     __u64 pad2[3];
 * }
 * }
 */
public class io_uring_cqwait_reg_arg {

    io_uring_cqwait_reg_arg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_INT.withName("flags"),
        uring_syscalls_h.C_INT.withName("struct_size"),
        uring_syscalls_h.C_INT.withName("nr_entries"),
        uring_syscalls_h.C_INT.withName("pad"),
        uring_syscalls_h.C_LONG_LONG.withName("user_addr"),
        MemoryLayout.sequenceLayout(3, uring_syscalls_h.C_LONG_LONG).withName("pad2")
    ).withName("io_uring_cqwait_reg_arg");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt struct_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("struct_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 struct_size
     * }
     */
    public static final OfInt struct_size$layout() {
        return struct_size$LAYOUT;
    }

    private static final long struct_size$OFFSET = $LAYOUT.byteOffset(groupElement("struct_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 struct_size
     * }
     */
    public static final long struct_size$offset() {
        return struct_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 struct_size
     * }
     */
    public static int struct_size(MemorySegment struct) {
        return struct.get(struct_size$LAYOUT, struct_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 struct_size
     * }
     */
    public static void struct_size(MemorySegment struct, int fieldValue) {
        struct.set(struct_size$LAYOUT, struct_size$OFFSET, fieldValue);
    }

    private static final OfInt nr_entries$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nr_entries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 nr_entries
     * }
     */
    public static final OfInt nr_entries$layout() {
        return nr_entries$LAYOUT;
    }

    private static final long nr_entries$OFFSET = $LAYOUT.byteOffset(groupElement("nr_entries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 nr_entries
     * }
     */
    public static final long nr_entries$offset() {
        return nr_entries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 nr_entries
     * }
     */
    public static int nr_entries(MemorySegment struct) {
        return struct.get(nr_entries$LAYOUT, nr_entries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 nr_entries
     * }
     */
    public static void nr_entries(MemorySegment struct, int fieldValue) {
        struct.set(nr_entries$LAYOUT, nr_entries$OFFSET, fieldValue);
    }

    private static final OfInt pad$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 pad
     * }
     */
    public static final OfInt pad$layout() {
        return pad$LAYOUT;
    }

    private static final long pad$OFFSET = $LAYOUT.byteOffset(groupElement("pad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 pad
     * }
     */
    public static final long pad$offset() {
        return pad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 pad
     * }
     */
    public static int pad(MemorySegment struct) {
        return struct.get(pad$LAYOUT, pad$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 pad
     * }
     */
    public static void pad(MemorySegment struct, int fieldValue) {
        struct.set(pad$LAYOUT, pad$OFFSET, fieldValue);
    }

    private static final OfLong user_addr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static final OfLong user_addr$layout() {
        return user_addr$LAYOUT;
    }

    private static final long user_addr$OFFSET = $LAYOUT.byteOffset(groupElement("user_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static final long user_addr$offset() {
        return user_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static long user_addr(MemorySegment struct) {
        return struct.get(user_addr$LAYOUT, user_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 user_addr
     * }
     */
    public static void user_addr(MemorySegment struct, long fieldValue) {
        struct.set(user_addr$LAYOUT, user_addr$OFFSET, fieldValue);
    }

    private static final SequenceLayout pad2$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("pad2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static final SequenceLayout pad2$layout() {
        return pad2$LAYOUT;
    }

    private static final long pad2$OFFSET = $LAYOUT.byteOffset(groupElement("pad2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static final long pad2$offset() {
        return pad2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static MemorySegment pad2(MemorySegment struct) {
        return struct.asSlice(pad2$OFFSET, pad2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static void pad2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pad2$OFFSET, pad2$LAYOUT.byteSize());
    }

    private static long[] pad2$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static long[] pad2$dimensions() {
        return pad2$DIMS;
    }
    private static final VarHandle pad2$ELEM_HANDLE = pad2$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static long pad2(MemorySegment struct, long index0) {
        return (long)pad2$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u64 pad2[3]
     * }
     */
    public static void pad2(MemorySegment struct, long index0, long fieldValue) {
        pad2$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

