// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_reg_wait {
 *     struct __kernel_timespec ts;
 *     __u32 min_wait_usec;
 *     __u32 flags;
 *     __u64 sigmask;
 *     __u32 sigmask_sz;
 *     __u32 pad[3];
 *     __u64 pad2[2];
 * }
 * }
 */
public class io_uring_reg_wait {

    io_uring_reg_wait() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        __kernel_timespec.layout().withName("ts"),
        uring_syscalls_h.C_INT.withName("min_wait_usec"),
        uring_syscalls_h.C_INT.withName("flags"),
        uring_syscalls_h.C_LONG_LONG.withName("sigmask"),
        uring_syscalls_h.C_INT.withName("sigmask_sz"),
        MemoryLayout.sequenceLayout(3, uring_syscalls_h.C_INT).withName("pad"),
        MemoryLayout.sequenceLayout(2, uring_syscalls_h.C_LONG_LONG).withName("pad2")
    ).withName("io_uring_reg_wait");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ts$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct __kernel_timespec ts
     * }
     */
    public static final GroupLayout ts$layout() {
        return ts$LAYOUT;
    }

    private static final long ts$OFFSET = $LAYOUT.byteOffset(groupElement("ts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct __kernel_timespec ts
     * }
     */
    public static final long ts$offset() {
        return ts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct __kernel_timespec ts
     * }
     */
    public static MemorySegment ts(MemorySegment struct) {
        return struct.asSlice(ts$OFFSET, ts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct __kernel_timespec ts
     * }
     */
    public static void ts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ts$OFFSET, ts$LAYOUT.byteSize());
    }

    private static final OfInt min_wait_usec$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_wait_usec"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 min_wait_usec
     * }
     */
    public static final OfInt min_wait_usec$layout() {
        return min_wait_usec$LAYOUT;
    }

    private static final long min_wait_usec$OFFSET = $LAYOUT.byteOffset(groupElement("min_wait_usec"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 min_wait_usec
     * }
     */
    public static final long min_wait_usec$offset() {
        return min_wait_usec$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 min_wait_usec
     * }
     */
    public static int min_wait_usec(MemorySegment struct) {
        return struct.get(min_wait_usec$LAYOUT, min_wait_usec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 min_wait_usec
     * }
     */
    public static void min_wait_usec(MemorySegment struct, int fieldValue) {
        struct.set(min_wait_usec$LAYOUT, min_wait_usec$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfLong sigmask$LAYOUT = (OfLong)$LAYOUT.select(groupElement("sigmask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 sigmask
     * }
     */
    public static final OfLong sigmask$layout() {
        return sigmask$LAYOUT;
    }

    private static final long sigmask$OFFSET = $LAYOUT.byteOffset(groupElement("sigmask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 sigmask
     * }
     */
    public static final long sigmask$offset() {
        return sigmask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 sigmask
     * }
     */
    public static long sigmask(MemorySegment struct) {
        return struct.get(sigmask$LAYOUT, sigmask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 sigmask
     * }
     */
    public static void sigmask(MemorySegment struct, long fieldValue) {
        struct.set(sigmask$LAYOUT, sigmask$OFFSET, fieldValue);
    }

    private static final OfInt sigmask_sz$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sigmask_sz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 sigmask_sz
     * }
     */
    public static final OfInt sigmask_sz$layout() {
        return sigmask_sz$LAYOUT;
    }

    private static final long sigmask_sz$OFFSET = $LAYOUT.byteOffset(groupElement("sigmask_sz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 sigmask_sz
     * }
     */
    public static final long sigmask_sz$offset() {
        return sigmask_sz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 sigmask_sz
     * }
     */
    public static int sigmask_sz(MemorySegment struct) {
        return struct.get(sigmask_sz$LAYOUT, sigmask_sz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 sigmask_sz
     * }
     */
    public static void sigmask_sz(MemorySegment struct, int fieldValue) {
        struct.set(sigmask_sz$LAYOUT, sigmask_sz$OFFSET, fieldValue);
    }

    private static final SequenceLayout pad$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("pad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static final SequenceLayout pad$layout() {
        return pad$LAYOUT;
    }

    private static final long pad$OFFSET = $LAYOUT.byteOffset(groupElement("pad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static final long pad$offset() {
        return pad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static MemorySegment pad(MemorySegment struct) {
        return struct.asSlice(pad$OFFSET, pad$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static void pad(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pad$OFFSET, pad$LAYOUT.byteSize());
    }

    private static long[] pad$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static long[] pad$dimensions() {
        return pad$DIMS;
    }
    private static final VarHandle pad$ELEM_HANDLE = pad$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static int pad(MemorySegment struct, long index0) {
        return (int)pad$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static void pad(MemorySegment struct, long index0, int fieldValue) {
        pad$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout pad2$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("pad2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static final SequenceLayout pad2$layout() {
        return pad2$LAYOUT;
    }

    private static final long pad2$OFFSET = $LAYOUT.byteOffset(groupElement("pad2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static final long pad2$offset() {
        return pad2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static MemorySegment pad2(MemorySegment struct) {
        return struct.asSlice(pad2$OFFSET, pad2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static void pad2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pad2$OFFSET, pad2$LAYOUT.byteSize());
    }

    private static long[] pad2$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static long[] pad2$dimensions() {
        return pad2$DIMS;
    }
    private static final VarHandle pad2$ELEM_HANDLE = pad2$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static long pad2(MemorySegment struct, long index0) {
        return (long)pad2$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u64 pad2[2]
     * }
     */
    public static void pad2(MemorySegment struct, long index0, long fieldValue) {
        pad2$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

