// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_clone_buffers {
 *     __u32 src_fd;
 *     __u32 flags;
 *     __u32 src_off;
 *     __u32 dst_off;
 *     __u32 nr;
 *     __u32 pad[3];
 * }
 * }
 */
public class io_uring_clone_buffers {

    io_uring_clone_buffers() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_INT.withName("src_fd"),
        uring_syscalls_h.C_INT.withName("flags"),
        uring_syscalls_h.C_INT.withName("src_off"),
        uring_syscalls_h.C_INT.withName("dst_off"),
        uring_syscalls_h.C_INT.withName("nr"),
        MemoryLayout.sequenceLayout(3, uring_syscalls_h.C_INT).withName("pad")
    ).withName("io_uring_clone_buffers");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt src_fd$LAYOUT = (OfInt)$LAYOUT.select(groupElement("src_fd"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 src_fd
     * }
     */
    public static final OfInt src_fd$layout() {
        return src_fd$LAYOUT;
    }

    private static final long src_fd$OFFSET = $LAYOUT.byteOffset(groupElement("src_fd"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 src_fd
     * }
     */
    public static final long src_fd$offset() {
        return src_fd$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 src_fd
     * }
     */
    public static int src_fd(MemorySegment struct) {
        return struct.get(src_fd$LAYOUT, src_fd$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 src_fd
     * }
     */
    public static void src_fd(MemorySegment struct, int fieldValue) {
        struct.set(src_fd$LAYOUT, src_fd$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = $LAYOUT.byteOffset(groupElement("flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfInt src_off$LAYOUT = (OfInt)$LAYOUT.select(groupElement("src_off"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 src_off
     * }
     */
    public static final OfInt src_off$layout() {
        return src_off$LAYOUT;
    }

    private static final long src_off$OFFSET = $LAYOUT.byteOffset(groupElement("src_off"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 src_off
     * }
     */
    public static final long src_off$offset() {
        return src_off$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 src_off
     * }
     */
    public static int src_off(MemorySegment struct) {
        return struct.get(src_off$LAYOUT, src_off$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 src_off
     * }
     */
    public static void src_off(MemorySegment struct, int fieldValue) {
        struct.set(src_off$LAYOUT, src_off$OFFSET, fieldValue);
    }

    private static final OfInt dst_off$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dst_off"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 dst_off
     * }
     */
    public static final OfInt dst_off$layout() {
        return dst_off$LAYOUT;
    }

    private static final long dst_off$OFFSET = $LAYOUT.byteOffset(groupElement("dst_off"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 dst_off
     * }
     */
    public static final long dst_off$offset() {
        return dst_off$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 dst_off
     * }
     */
    public static int dst_off(MemorySegment struct) {
        return struct.get(dst_off$LAYOUT, dst_off$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 dst_off
     * }
     */
    public static void dst_off(MemorySegment struct, int fieldValue) {
        struct.set(dst_off$LAYOUT, dst_off$OFFSET, fieldValue);
    }

    private static final OfInt nr$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 nr
     * }
     */
    public static final OfInt nr$layout() {
        return nr$LAYOUT;
    }

    private static final long nr$OFFSET = $LAYOUT.byteOffset(groupElement("nr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 nr
     * }
     */
    public static final long nr$offset() {
        return nr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 nr
     * }
     */
    public static int nr(MemorySegment struct) {
        return struct.get(nr$LAYOUT, nr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 nr
     * }
     */
    public static void nr(MemorySegment struct, int fieldValue) {
        struct.set(nr$LAYOUT, nr$OFFSET, fieldValue);
    }

    private static final SequenceLayout pad$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("pad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static final SequenceLayout pad$layout() {
        return pad$LAYOUT;
    }

    private static final long pad$OFFSET = $LAYOUT.byteOffset(groupElement("pad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static final long pad$offset() {
        return pad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static MemorySegment pad(MemorySegment struct) {
        return struct.asSlice(pad$OFFSET, pad$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static void pad(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pad$OFFSET, pad$LAYOUT.byteSize());
    }

    private static long[] pad$DIMS = { 3 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static long[] pad$dimensions() {
        return pad$DIMS;
    }
    private static final VarHandle pad$ELEM_HANDLE = pad$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static int pad(MemorySegment struct, long index0) {
        return (int)pad$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u32 pad[3]
     * }
     */
    public static void pad(MemorySegment struct, long index0, int fieldValue) {
        pad$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

