// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct io_uring_cq {
 *     unsigned int *khead;
 *     unsigned int *ktail;
 *     unsigned int *kring_mask;
 *     unsigned int *kring_entries;
 *     unsigned int *kflags;
 *     unsigned int *koverflow;
 *     struct io_uring_cqe *cqes;
 *     size_t ring_sz;
 *     void *ring_ptr;
 *     unsigned int ring_mask;
 *     unsigned int ring_entries;
 *     unsigned int pad[2];
 * }
 * }
 */
public class io_uring_cq {

    io_uring_cq() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_POINTER.withName("khead"),
        uring_syscalls_h.C_POINTER.withName("ktail"),
        uring_syscalls_h.C_POINTER.withName("kring_mask"),
        uring_syscalls_h.C_POINTER.withName("kring_entries"),
        uring_syscalls_h.C_POINTER.withName("kflags"),
        uring_syscalls_h.C_POINTER.withName("koverflow"),
        uring_syscalls_h.C_POINTER.withName("cqes"),
        uring_syscalls_h.C_LONG.withName("ring_sz"),
        uring_syscalls_h.C_POINTER.withName("ring_ptr"),
        uring_syscalls_h.C_INT.withName("ring_mask"),
        uring_syscalls_h.C_INT.withName("ring_entries"),
        MemoryLayout.sequenceLayout(2, uring_syscalls_h.C_INT).withName("pad")
    ).withName("io_uring_cq");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout khead$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("khead"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *khead
     * }
     */
    public static final AddressLayout khead$layout() {
        return khead$LAYOUT;
    }

    private static final long khead$OFFSET = $LAYOUT.byteOffset(groupElement("khead"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *khead
     * }
     */
    public static final long khead$offset() {
        return khead$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *khead
     * }
     */
    public static MemorySegment khead(MemorySegment struct) {
        return struct.get(khead$LAYOUT, khead$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *khead
     * }
     */
    public static void khead(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(khead$LAYOUT, khead$OFFSET, fieldValue);
    }

    private static final AddressLayout ktail$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ktail"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *ktail
     * }
     */
    public static final AddressLayout ktail$layout() {
        return ktail$LAYOUT;
    }

    private static final long ktail$OFFSET = $LAYOUT.byteOffset(groupElement("ktail"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *ktail
     * }
     */
    public static final long ktail$offset() {
        return ktail$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *ktail
     * }
     */
    public static MemorySegment ktail(MemorySegment struct) {
        return struct.get(ktail$LAYOUT, ktail$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *ktail
     * }
     */
    public static void ktail(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ktail$LAYOUT, ktail$OFFSET, fieldValue);
    }

    private static final AddressLayout kring_mask$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("kring_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *kring_mask
     * }
     */
    public static final AddressLayout kring_mask$layout() {
        return kring_mask$LAYOUT;
    }

    private static final long kring_mask$OFFSET = $LAYOUT.byteOffset(groupElement("kring_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *kring_mask
     * }
     */
    public static final long kring_mask$offset() {
        return kring_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *kring_mask
     * }
     */
    public static MemorySegment kring_mask(MemorySegment struct) {
        return struct.get(kring_mask$LAYOUT, kring_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *kring_mask
     * }
     */
    public static void kring_mask(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(kring_mask$LAYOUT, kring_mask$OFFSET, fieldValue);
    }

    private static final AddressLayout kring_entries$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("kring_entries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *kring_entries
     * }
     */
    public static final AddressLayout kring_entries$layout() {
        return kring_entries$LAYOUT;
    }

    private static final long kring_entries$OFFSET = $LAYOUT.byteOffset(groupElement("kring_entries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *kring_entries
     * }
     */
    public static final long kring_entries$offset() {
        return kring_entries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *kring_entries
     * }
     */
    public static MemorySegment kring_entries(MemorySegment struct) {
        return struct.get(kring_entries$LAYOUT, kring_entries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *kring_entries
     * }
     */
    public static void kring_entries(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(kring_entries$LAYOUT, kring_entries$OFFSET, fieldValue);
    }

    private static final AddressLayout kflags$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("kflags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *kflags
     * }
     */
    public static final AddressLayout kflags$layout() {
        return kflags$LAYOUT;
    }

    private static final long kflags$OFFSET = $LAYOUT.byteOffset(groupElement("kflags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *kflags
     * }
     */
    public static final long kflags$offset() {
        return kflags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *kflags
     * }
     */
    public static MemorySegment kflags(MemorySegment struct) {
        return struct.get(kflags$LAYOUT, kflags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *kflags
     * }
     */
    public static void kflags(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(kflags$LAYOUT, kflags$OFFSET, fieldValue);
    }

    private static final AddressLayout koverflow$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("koverflow"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int *koverflow
     * }
     */
    public static final AddressLayout koverflow$layout() {
        return koverflow$LAYOUT;
    }

    private static final long koverflow$OFFSET = $LAYOUT.byteOffset(groupElement("koverflow"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int *koverflow
     * }
     */
    public static final long koverflow$offset() {
        return koverflow$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int *koverflow
     * }
     */
    public static MemorySegment koverflow(MemorySegment struct) {
        return struct.get(koverflow$LAYOUT, koverflow$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int *koverflow
     * }
     */
    public static void koverflow(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(koverflow$LAYOUT, koverflow$OFFSET, fieldValue);
    }

    private static final AddressLayout cqes$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("cqes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct io_uring_cqe *cqes
     * }
     */
    public static final AddressLayout cqes$layout() {
        return cqes$LAYOUT;
    }

    private static final long cqes$OFFSET = $LAYOUT.byteOffset(groupElement("cqes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct io_uring_cqe *cqes
     * }
     */
    public static final long cqes$offset() {
        return cqes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct io_uring_cqe *cqes
     * }
     */
    public static MemorySegment cqes(MemorySegment struct) {
        return struct.get(cqes$LAYOUT, cqes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct io_uring_cqe *cqes
     * }
     */
    public static void cqes(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(cqes$LAYOUT, cqes$OFFSET, fieldValue);
    }

    private static final OfLong ring_sz$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ring_sz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t ring_sz
     * }
     */
    public static final OfLong ring_sz$layout() {
        return ring_sz$LAYOUT;
    }

    private static final long ring_sz$OFFSET = $LAYOUT.byteOffset(groupElement("ring_sz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t ring_sz
     * }
     */
    public static final long ring_sz$offset() {
        return ring_sz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t ring_sz
     * }
     */
    public static long ring_sz(MemorySegment struct) {
        return struct.get(ring_sz$LAYOUT, ring_sz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t ring_sz
     * }
     */
    public static void ring_sz(MemorySegment struct, long fieldValue) {
        struct.set(ring_sz$LAYOUT, ring_sz$OFFSET, fieldValue);
    }

    private static final AddressLayout ring_ptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ring_ptr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *ring_ptr
     * }
     */
    public static final AddressLayout ring_ptr$layout() {
        return ring_ptr$LAYOUT;
    }

    private static final long ring_ptr$OFFSET = $LAYOUT.byteOffset(groupElement("ring_ptr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *ring_ptr
     * }
     */
    public static final long ring_ptr$offset() {
        return ring_ptr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *ring_ptr
     * }
     */
    public static MemorySegment ring_ptr(MemorySegment struct) {
        return struct.get(ring_ptr$LAYOUT, ring_ptr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *ring_ptr
     * }
     */
    public static void ring_ptr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ring_ptr$LAYOUT, ring_ptr$OFFSET, fieldValue);
    }

    private static final OfInt ring_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ring_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int ring_mask
     * }
     */
    public static final OfInt ring_mask$layout() {
        return ring_mask$LAYOUT;
    }

    private static final long ring_mask$OFFSET = $LAYOUT.byteOffset(groupElement("ring_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int ring_mask
     * }
     */
    public static final long ring_mask$offset() {
        return ring_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int ring_mask
     * }
     */
    public static int ring_mask(MemorySegment struct) {
        return struct.get(ring_mask$LAYOUT, ring_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int ring_mask
     * }
     */
    public static void ring_mask(MemorySegment struct, int fieldValue) {
        struct.set(ring_mask$LAYOUT, ring_mask$OFFSET, fieldValue);
    }

    private static final OfInt ring_entries$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ring_entries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int ring_entries
     * }
     */
    public static final OfInt ring_entries$layout() {
        return ring_entries$LAYOUT;
    }

    private static final long ring_entries$OFFSET = $LAYOUT.byteOffset(groupElement("ring_entries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int ring_entries
     * }
     */
    public static final long ring_entries$offset() {
        return ring_entries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int ring_entries
     * }
     */
    public static int ring_entries(MemorySegment struct) {
        return struct.get(ring_entries$LAYOUT, ring_entries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int ring_entries
     * }
     */
    public static void ring_entries(MemorySegment struct, int fieldValue) {
        struct.set(ring_entries$LAYOUT, ring_entries$OFFSET, fieldValue);
    }

    private static final SequenceLayout pad$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("pad"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static final SequenceLayout pad$layout() {
        return pad$LAYOUT;
    }

    private static final long pad$OFFSET = $LAYOUT.byteOffset(groupElement("pad"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static final long pad$offset() {
        return pad$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static MemorySegment pad(MemorySegment struct) {
        return struct.asSlice(pad$OFFSET, pad$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static void pad(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pad$OFFSET, pad$LAYOUT.byteSize());
    }

    private static long[] pad$DIMS = { 2 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static long[] pad$dimensions() {
        return pad$DIMS;
    }
    private static final VarHandle pad$ELEM_HANDLE = pad$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static int pad(MemorySegment struct, long index0) {
        return (int)pad$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned int pad[2]
     * }
     */
    public static void pad(MemorySegment struct, long index0, int fieldValue) {
        pad$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

