// Generated by jextract

package sockets.rawcalls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct procmap_query {
 *     __u64 size;
 *     __u64 query_flags;
 *     __u64 query_addr;
 *     __u64 vma_start;
 *     __u64 vma_end;
 *     __u64 vma_flags;
 *     __u64 vma_page_size;
 *     __u64 vma_offset;
 *     __u64 inode;
 *     __u32 dev_major;
 *     __u32 dev_minor;
 *     __u32 vma_name_size;
 *     __u32 build_id_size;
 *     __u64 vma_name_addr;
 *     __u64 build_id_addr;
 * }
 * }
 */
public class procmap_query {

    procmap_query() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        uring_syscalls_h.C_LONG_LONG.withName("size"),
        uring_syscalls_h.C_LONG_LONG.withName("query_flags"),
        uring_syscalls_h.C_LONG_LONG.withName("query_addr"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_start"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_end"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_flags"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_page_size"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_offset"),
        uring_syscalls_h.C_LONG_LONG.withName("inode"),
        uring_syscalls_h.C_INT.withName("dev_major"),
        uring_syscalls_h.C_INT.withName("dev_minor"),
        uring_syscalls_h.C_INT.withName("vma_name_size"),
        uring_syscalls_h.C_INT.withName("build_id_size"),
        uring_syscalls_h.C_LONG_LONG.withName("vma_name_addr"),
        uring_syscalls_h.C_LONG_LONG.withName("build_id_addr")
    ).withName("procmap_query");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static final OfLong size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static long size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 size
     * }
     */
    public static void size(MemorySegment struct, long fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfLong query_flags$LAYOUT = (OfLong)$LAYOUT.select(groupElement("query_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 query_flags
     * }
     */
    public static final OfLong query_flags$layout() {
        return query_flags$LAYOUT;
    }

    private static final long query_flags$OFFSET = $LAYOUT.byteOffset(groupElement("query_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 query_flags
     * }
     */
    public static final long query_flags$offset() {
        return query_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 query_flags
     * }
     */
    public static long query_flags(MemorySegment struct) {
        return struct.get(query_flags$LAYOUT, query_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 query_flags
     * }
     */
    public static void query_flags(MemorySegment struct, long fieldValue) {
        struct.set(query_flags$LAYOUT, query_flags$OFFSET, fieldValue);
    }

    private static final OfLong query_addr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("query_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 query_addr
     * }
     */
    public static final OfLong query_addr$layout() {
        return query_addr$LAYOUT;
    }

    private static final long query_addr$OFFSET = $LAYOUT.byteOffset(groupElement("query_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 query_addr
     * }
     */
    public static final long query_addr$offset() {
        return query_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 query_addr
     * }
     */
    public static long query_addr(MemorySegment struct) {
        return struct.get(query_addr$LAYOUT, query_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 query_addr
     * }
     */
    public static void query_addr(MemorySegment struct, long fieldValue) {
        struct.set(query_addr$LAYOUT, query_addr$OFFSET, fieldValue);
    }

    private static final OfLong vma_start$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_start"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_start
     * }
     */
    public static final OfLong vma_start$layout() {
        return vma_start$LAYOUT;
    }

    private static final long vma_start$OFFSET = $LAYOUT.byteOffset(groupElement("vma_start"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_start
     * }
     */
    public static final long vma_start$offset() {
        return vma_start$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_start
     * }
     */
    public static long vma_start(MemorySegment struct) {
        return struct.get(vma_start$LAYOUT, vma_start$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_start
     * }
     */
    public static void vma_start(MemorySegment struct, long fieldValue) {
        struct.set(vma_start$LAYOUT, vma_start$OFFSET, fieldValue);
    }

    private static final OfLong vma_end$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_end"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_end
     * }
     */
    public static final OfLong vma_end$layout() {
        return vma_end$LAYOUT;
    }

    private static final long vma_end$OFFSET = $LAYOUT.byteOffset(groupElement("vma_end"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_end
     * }
     */
    public static final long vma_end$offset() {
        return vma_end$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_end
     * }
     */
    public static long vma_end(MemorySegment struct) {
        return struct.get(vma_end$LAYOUT, vma_end$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_end
     * }
     */
    public static void vma_end(MemorySegment struct, long fieldValue) {
        struct.set(vma_end$LAYOUT, vma_end$OFFSET, fieldValue);
    }

    private static final OfLong vma_flags$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_flags
     * }
     */
    public static final OfLong vma_flags$layout() {
        return vma_flags$LAYOUT;
    }

    private static final long vma_flags$OFFSET = $LAYOUT.byteOffset(groupElement("vma_flags"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_flags
     * }
     */
    public static final long vma_flags$offset() {
        return vma_flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_flags
     * }
     */
    public static long vma_flags(MemorySegment struct) {
        return struct.get(vma_flags$LAYOUT, vma_flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_flags
     * }
     */
    public static void vma_flags(MemorySegment struct, long fieldValue) {
        struct.set(vma_flags$LAYOUT, vma_flags$OFFSET, fieldValue);
    }

    private static final OfLong vma_page_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_page_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_page_size
     * }
     */
    public static final OfLong vma_page_size$layout() {
        return vma_page_size$LAYOUT;
    }

    private static final long vma_page_size$OFFSET = $LAYOUT.byteOffset(groupElement("vma_page_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_page_size
     * }
     */
    public static final long vma_page_size$offset() {
        return vma_page_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_page_size
     * }
     */
    public static long vma_page_size(MemorySegment struct) {
        return struct.get(vma_page_size$LAYOUT, vma_page_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_page_size
     * }
     */
    public static void vma_page_size(MemorySegment struct, long fieldValue) {
        struct.set(vma_page_size$LAYOUT, vma_page_size$OFFSET, fieldValue);
    }

    private static final OfLong vma_offset$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_offset
     * }
     */
    public static final OfLong vma_offset$layout() {
        return vma_offset$LAYOUT;
    }

    private static final long vma_offset$OFFSET = $LAYOUT.byteOffset(groupElement("vma_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_offset
     * }
     */
    public static final long vma_offset$offset() {
        return vma_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_offset
     * }
     */
    public static long vma_offset(MemorySegment struct) {
        return struct.get(vma_offset$LAYOUT, vma_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_offset
     * }
     */
    public static void vma_offset(MemorySegment struct, long fieldValue) {
        struct.set(vma_offset$LAYOUT, vma_offset$OFFSET, fieldValue);
    }

    private static final OfLong inode$LAYOUT = (OfLong)$LAYOUT.select(groupElement("inode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 inode
     * }
     */
    public static final OfLong inode$layout() {
        return inode$LAYOUT;
    }

    private static final long inode$OFFSET = $LAYOUT.byteOffset(groupElement("inode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 inode
     * }
     */
    public static final long inode$offset() {
        return inode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 inode
     * }
     */
    public static long inode(MemorySegment struct) {
        return struct.get(inode$LAYOUT, inode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 inode
     * }
     */
    public static void inode(MemorySegment struct, long fieldValue) {
        struct.set(inode$LAYOUT, inode$OFFSET, fieldValue);
    }

    private static final OfInt dev_major$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dev_major"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 dev_major
     * }
     */
    public static final OfInt dev_major$layout() {
        return dev_major$LAYOUT;
    }

    private static final long dev_major$OFFSET = $LAYOUT.byteOffset(groupElement("dev_major"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 dev_major
     * }
     */
    public static final long dev_major$offset() {
        return dev_major$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 dev_major
     * }
     */
    public static int dev_major(MemorySegment struct) {
        return struct.get(dev_major$LAYOUT, dev_major$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 dev_major
     * }
     */
    public static void dev_major(MemorySegment struct, int fieldValue) {
        struct.set(dev_major$LAYOUT, dev_major$OFFSET, fieldValue);
    }

    private static final OfInt dev_minor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("dev_minor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 dev_minor
     * }
     */
    public static final OfInt dev_minor$layout() {
        return dev_minor$LAYOUT;
    }

    private static final long dev_minor$OFFSET = $LAYOUT.byteOffset(groupElement("dev_minor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 dev_minor
     * }
     */
    public static final long dev_minor$offset() {
        return dev_minor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 dev_minor
     * }
     */
    public static int dev_minor(MemorySegment struct) {
        return struct.get(dev_minor$LAYOUT, dev_minor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 dev_minor
     * }
     */
    public static void dev_minor(MemorySegment struct, int fieldValue) {
        struct.set(dev_minor$LAYOUT, dev_minor$OFFSET, fieldValue);
    }

    private static final OfInt vma_name_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("vma_name_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 vma_name_size
     * }
     */
    public static final OfInt vma_name_size$layout() {
        return vma_name_size$LAYOUT;
    }

    private static final long vma_name_size$OFFSET = $LAYOUT.byteOffset(groupElement("vma_name_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 vma_name_size
     * }
     */
    public static final long vma_name_size$offset() {
        return vma_name_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 vma_name_size
     * }
     */
    public static int vma_name_size(MemorySegment struct) {
        return struct.get(vma_name_size$LAYOUT, vma_name_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 vma_name_size
     * }
     */
    public static void vma_name_size(MemorySegment struct, int fieldValue) {
        struct.set(vma_name_size$LAYOUT, vma_name_size$OFFSET, fieldValue);
    }

    private static final OfInt build_id_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("build_id_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 build_id_size
     * }
     */
    public static final OfInt build_id_size$layout() {
        return build_id_size$LAYOUT;
    }

    private static final long build_id_size$OFFSET = $LAYOUT.byteOffset(groupElement("build_id_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 build_id_size
     * }
     */
    public static final long build_id_size$offset() {
        return build_id_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 build_id_size
     * }
     */
    public static int build_id_size(MemorySegment struct) {
        return struct.get(build_id_size$LAYOUT, build_id_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 build_id_size
     * }
     */
    public static void build_id_size(MemorySegment struct, int fieldValue) {
        struct.set(build_id_size$LAYOUT, build_id_size$OFFSET, fieldValue);
    }

    private static final OfLong vma_name_addr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vma_name_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 vma_name_addr
     * }
     */
    public static final OfLong vma_name_addr$layout() {
        return vma_name_addr$LAYOUT;
    }

    private static final long vma_name_addr$OFFSET = $LAYOUT.byteOffset(groupElement("vma_name_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 vma_name_addr
     * }
     */
    public static final long vma_name_addr$offset() {
        return vma_name_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 vma_name_addr
     * }
     */
    public static long vma_name_addr(MemorySegment struct) {
        return struct.get(vma_name_addr$LAYOUT, vma_name_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 vma_name_addr
     * }
     */
    public static void vma_name_addr(MemorySegment struct, long fieldValue) {
        struct.set(vma_name_addr$LAYOUT, vma_name_addr$OFFSET, fieldValue);
    }

    private static final OfLong build_id_addr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("build_id_addr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 build_id_addr
     * }
     */
    public static final OfLong build_id_addr$layout() {
        return build_id_addr$LAYOUT;
    }

    private static final long build_id_addr$OFFSET = $LAYOUT.byteOffset(groupElement("build_id_addr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 build_id_addr
     * }
     */
    public static final long build_id_addr$offset() {
        return build_id_addr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 build_id_addr
     * }
     */
    public static long build_id_addr(MemorySegment struct) {
        return struct.get(build_id_addr$LAYOUT, build_id_addr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 build_id_addr
     * }
     */
    public static void build_id_addr(MemorySegment struct, long fieldValue) {
        struct.set(build_id_addr$LAYOUT, build_id_addr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

